name: Build Docs
on:
  workflow_call:
jobs:
  build:
    name: Build Docs
    runs-on: blacksmith-4vcpu-ubuntu-2204
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dangerous-git-checkout

      - name: Setup Node.js 20.x
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 20.x

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --config.platform=linux --config.architecture=x64
        shell: bash

      - run: |
          pnpm build --filter=@formbricks/docs...
        shell: bash
